/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Arbol;
import java.awt.Color;
import Logica.Nodo;

/**
 * Uned Alaljuela - Alonso Guevara
 * Clase formulario para el manejo general de la APP
 * General.java fecha de creacion  10/4/2026
 */
public class General extends javax.swing.JFrame {

    private Arbol arbol;
    private PanelArbol panelArbol;
    private javax.swing.JScrollPane scrollArbol;
    
    public General() {
        initComponents();
        
        arbol = new Arbol();
        cargarCategorias();
        txtEstado.setEditable(false);
        txaDatos.setEditable(false);

        panelArbol = new PanelArbol();
        panelArbol.setArbol(arbol);
        
        scrollArbol = new javax.swing.JScrollPane(panelArbol);
        scrollArbol.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollArbol.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        
        pnlGrafica.setLayout(new java.awt.BorderLayout());
        pnlGrafica.removeAll();
        pnlGrafica.add(scrollArbol, java.awt.BorderLayout.CENTER);
        pnlGrafica.revalidate();
        pnlGrafica.repaint();
        
        centrarScrollArbol();

    }
    
    //Metodos Auxiliares
    
     private void cargarCategorias(){
        cmbCategoria.removeAllItems();
        
        cmbCategoria.addItem("Seleccione...");
        cmbCategoria.addItem("Civiles");
        cmbCategoria.addItem("Equipos");
        cmbCategoria.addItem("Super Heroes");
        cmbCategoria.addItem("Objetos");
        cmbCategoria.addItem("Super Villanos");
        cmbCategoria.addItem("Paneles");
        cmbCategoria.addItem("Cara a Cara");
        cmbCategoria.addItem("Frases Iconicas");
        cmbCategoria.addItem("Pelicula Especial");
    }
     
    private void limpiarCampos() {
        txtId.setText("");
        txtDescripcion.setText("");
        cmbCategoria.setSelectedIndex(0);
        txtId.requestFocus();
    }
    
    private void mostrarEstadoTemporal(String mensaje, Color color) {

        txtEstado.setForeground(color);
        txtEstado.setText(mensaje);

        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
            txtEstado.setForeground(Color.BLUE);
            txtEstado.setText("En espera");
        });

        timer.setRepeats(false);
        timer.start();
    }
    
    private void centrarScrollArbol() {
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JScrollBar barraHorizontal = scrollArbol.getHorizontalScrollBar();
            javax.swing.JScrollBar barraVertical = scrollArbol.getVerticalScrollBar();

            int centroX = (barraHorizontal.getMaximum() - barraHorizontal.getVisibleAmount()) / 2;

            barraHorizontal.setValue(Math.max(0, centroX));
            barraVertical.setValue(0);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatos = new javax.swing.JTextArea();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnPreorden = new javax.swing.JButton();
        btnPostOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnCantidadNodos = new javax.swing.JButton();
        btnListarNodosHojas = new javax.swing.JButton();
        btnMayorMenor = new javax.swing.JButton();
        btnConsultasAdicionales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arbol Binario de Busqueda");

        jLabel1.setText("ID");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Categoria");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txaDatos.setColumns(20);
        txaDatos.setRows(5);
        jScrollPane1.setViewportView(txaDatos);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPreorden.setBackground(new java.awt.Color(0, 102, 102));
        btnPreorden.setForeground(new java.awt.Color(255, 255, 255));
        btnPreorden.setText("Pre-Orden");
        btnPreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreordenActionPerformed(evt);
            }
        });

        btnPostOrden.setBackground(new java.awt.Color(0, 102, 102));
        btnPostOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPostOrden.setText("Post-Orden");
        btnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrdenActionPerformed(evt);
            }
        });

        btnInOrden.setBackground(new java.awt.Color(0, 102, 102));
        btnInOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnInOrden.setText("In-Orden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });

        btnCantidadNodos.setBackground(new java.awt.Color(0, 102, 102));
        btnCantidadNodos.setForeground(new java.awt.Color(255, 255, 255));
        btnCantidadNodos.setText("Cantida Nodos");
        btnCantidadNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadNodosActionPerformed(evt);
            }
        });

        btnListarNodosHojas.setBackground(new java.awt.Color(0, 102, 102));
        btnListarNodosHojas.setForeground(new java.awt.Color(255, 255, 255));
        btnListarNodosHojas.setText("Listar Nodos H");
        btnListarNodosHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarNodosHojasActionPerformed(evt);
            }
        });

        btnMayorMenor.setBackground(new java.awt.Color(0, 102, 102));
        btnMayorMenor.setForeground(new java.awt.Color(255, 255, 255));
        btnMayorMenor.setText("Mayor y Menor");
        btnMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorMenorActionPerformed(evt);
            }
        });

        btnConsultasAdicionales.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultasAdicionales.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultasAdicionales.setText("Consultas Extra");
        btnConsultasAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasAdicionalesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("DC Comics");

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeneralLayout.createSequentialGroup()
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstado)
                            .addComponent(txtDescripcion)
                            .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlGeneralLayout.createSequentialGroup()
                                .addComponent(btnInsertar)
                                .addGap(29, 29, 29)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPreorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPostOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCantidadNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarNodosHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMayorMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultasAdicionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addComponent(btnPreorden)
                        .addGap(18, 18, 18)
                        .addComponent(btnPostOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnInOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnCantidadNodos)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarNodosHojas)
                        .addGap(18, 18, 18)
                        .addComponent(btnMayorMenor))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultasAdicionales)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(btnInsertar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlGrafica.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrafica.setForeground(new java.awt.Color(255, 255, 255));
        pnlGrafica.setPreferredSize(new java.awt.Dimension(441, 458));
        pnlGrafica.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlGraficaLayout = new javax.swing.GroupLayout(pnlGrafica);
        pnlGrafica.setLayout(pnlGraficaLayout);
        pnlGraficaLayout.setHorizontalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        pnlGraficaLayout.setVerticalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Botones de comandos
    
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        
        String idTexto = txtId.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        String categoria = cmbCategoria.getSelectedItem().toString().trim();
        
        //Validacion de datos
        
        if(idTexto.isEmpty()||descripcion.isEmpty()||categoria.equalsIgnoreCase("Seleccione...")){
            mostrarEstadoTemporal("Todos los campos son obligatorios",Color.RED);
            return;
        }
        
        if (!descripcion.matches(".*[a-zA-Z].*")) {
            mostrarEstadoTemporal("El Campo descripcion debe contener Letras",Color.RED);
            return;
        }
        
        int id;
        
        try{
            
            id = Integer.parseInt(idTexto);
            
        }catch(NumberFormatException e){
            
            mostrarEstadoTemporal("El Id Debe ser un numero Entero",Color.RED);
            return;
        }
        
        if(id <= 0){
            mostrarEstadoTemporal("El Id Debe ser un numero Positivo",Color.RED);
            return;
        }
        
        //Se crea esta validacion para mejorar la parte grafica, no es un requerimiento del proyecto como tal.
        if(id > 999){
            mostrarEstadoTemporal("El Id no puede tener mas de 3 Digitos",Color.RED);
            return;
        }
        
        //Creacion de la clase Tarjeta e insercion en el arbol
        
        Entidad.Tarjeta tarjeta = new Entidad.Tarjeta(id, descripcion, categoria);
        
        if(arbol.insertar(tarjeta)){
            mostrarEstadoTemporal("Tarjeta Insertada Correctamente",Color.green);
            limpiarCampos();
            panelArbol.revalidate();
            panelArbol.setNodoResaltado(null);
            panelArbol.repaint();
            scrollArbol.revalidate();
            scrollArbol.repaint();
            centrarScrollArbol();
            txaDatos.setText("");
        }else{
            mostrarEstadoTemporal("El ID ya existe en el arbol",Color.RED);
        }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idTexto = txtId.getText().trim();
        
        if(idTexto.isEmpty()){
            mostrarEstadoTemporal("Ingresar un ID para buscar", Color.RED);
            return;
        }
        
        int id;
        
        try{
            
            id = Integer.parseInt(idTexto);
            
        }catch(NumberFormatException e){
            
            mostrarEstadoTemporal("El ID debe ser un numero Entero",Color.RED);
            return;
        }
        if(id <= 0){
            mostrarEstadoTemporal("El ID debe ser un numero Positivo",Color.RED);
            return;
        }
        
        Nodo encontrado = arbol.buscar(id);
        
        if (encontrado != null){
            
            panelArbol.setNodoResaltado(encontrado);
            panelArbol.repaint();
            
            txaDatos.setText(                    
                "ID: " + encontrado.getDato().getId() +
                "\nDescripcion: " + encontrado.getDato().getDescripcion() +
                "\nCategoria: " + encontrado.getDato().getCategoria() +
                "\n" + "\n !!! Puedes ver la posicion del nodo en azul !!! "
            );
            
            mostrarEstadoTemporal("Nodo Encontrado", Color.GREEN);
        }else{
            
            panelArbol.setNodoResaltado(null);
            panelArbol.repaint();

            txaDatos.setText("");
            mostrarEstadoTemporal("ID no encontrado", Color.RED);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreordenActionPerformed
         if (arbol.estaVacio()) {
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            txaDatos.setText("");
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        String recorrido = arbol.preOrden();

        txaDatos.setText("RECORRIDO PREORDEN POR ID\n\n" + recorrido);
        mostrarEstadoTemporal("Recorrido Preorden generado", Color.GREEN);
    }//GEN-LAST:event_btnPreordenActionPerformed

    private void btnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrdenActionPerformed
        if (arbol.estaVacio()) {
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            txaDatos.setText("");
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        String recorrido = arbol.postOrden();

        txaDatos.setText("RECORRIDO POSTORDEN POR ID\n\n" + recorrido);
        mostrarEstadoTemporal("Recorrido Postorden generado", Color.GREEN);
    }//GEN-LAST:event_btnPostOrdenActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        if (arbol.estaVacio()) {
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            txaDatos.setText("");
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        String recorrido = arbol.inOrden();

        txaDatos.setText("RECORRIDO INORDEN POR ID\n\n" + recorrido);
        mostrarEstadoTemporal("Recorrido Inorden generado", Color.GREEN);
    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
       String idTexto = txtId.getText().trim();

        if (idTexto.isEmpty()) {
            mostrarEstadoTemporal("Ingrese un ID para eliminar", Color.RED);
            return;
        }

        int id;

        try {
            id = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            mostrarEstadoTemporal("El ID debe ser un numero entero", Color.RED);
            return;
        }

        if (id <= 0) {
            mostrarEstadoTemporal("El ID debe ser un numero positivo", Color.RED);
            return;
        }

        String resultado = arbol.eliminar(id);

        if (resultado.equals("Nodo eliminado correctamente")) {
            panelArbol.setNodoResaltado(null);
            panelArbol.revalidate();
            panelArbol.repaint();
            scrollArbol.revalidate();
            scrollArbol.repaint();

            txaDatos.setText("");
            mostrarEstadoTemporal(resultado, Color.GREEN);
        } else {
            mostrarEstadoTemporal(resultado, Color.RED);
        } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCantidadNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadNodosActionPerformed
        
        if(arbol.estaVacio()){
            txaDatos.setText("");
            mostrarEstadoTemporal("El Arbol esta Vacio", Color.RED);
            return;
        }
        
        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();
        
        int cI = arbol.contarPorCategoria("Civiles");
        int eQ = arbol.contarPorCategoria("Equipos");
        int sH = arbol.contarPorCategoria("Super Heroes");
        int oB = arbol.contarPorCategoria("Objetos");
        int sV = arbol.contarPorCategoria("Super Villanos");
        int pA = arbol.contarPorCategoria("Paneles");
        int cC = arbol.contarPorCategoria("Cara a Cara");
        int fI = arbol.contarPorCategoria("Frases Iconicas");
        int pE = arbol.contarPorCategoria("Pelicula Especial");
        
        int totalCompuesto = sH+sV;
        int total = cI+eQ+sH+oB+sV+pA+cC+fI+pE;
        
        double porcentajeSuperHeroes = ((double)sH/total)*100;
        double porcentajeSuperVillanos = ((double)sV/total)*100;
        double porcentajeCompuesto = ((double)totalCompuesto/total)*100;
        
        txaDatos.setText(
                
            "CANTIDAD DE NODOS POR CATEGORIA\n\n" +
            "Super Heroes: " + sH + " | Porcentaje ocupado: " + String.format("%.1f", porcentajeSuperHeroes) + "%\n" +
            "Super Villanos: " + sV + " | Porcentaje ocupado: " + String.format("%.1f", porcentajeSuperVillanos) + "%\n" +
            "Total Compuesto: " + totalCompuesto + " | Porcentaje ocupado: " + String.format("%.1f", porcentajeCompuesto) + "%\n" +
            "Total de Nodos en el Arbol: " + total
        );
        
        mostrarEstadoTemporal("Conteo generado correctamente", Color.GREEN);
    }//GEN-LAST:event_btnCantidadNodosActionPerformed

    private void btnListarNodosHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarNodosHojasActionPerformed
        
        if (arbol.estaVacio()) {
            txaDatos.setText("");
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        String lista = arbol.listarFrIc();

        txaDatos.setText(
                
            "LISTA DE NODOS HOJA\n" +
            "CATEGORIA: FRASES ICONICAS\n\n" +
            lista
        );

        mostrarEstadoTemporal("Consulta generada correctamente", Color.BLUE);
    
    }//GEN-LAST:event_btnListarNodosHojasActionPerformed

    private void btnMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorMenorActionPerformed
        
        if (arbol.estaVacio()) {
            txaDatos.setText("");
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        String resultado = arbol.obtenerMayorYMenor();

        txaDatos.setText(resultado);
        mostrarEstadoTemporal("Consulta generada correctamente", Color.GREEN);
    }//GEN-LAST:event_btnMayorMenorActionPerformed

    private void btnConsultasAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasAdicionalesActionPerformed
         if (arbol.estaVacio()) {
            txaDatos.setText("");
            mostrarEstadoTemporal("El arbol esta vacio", Color.RED);
            return;
        }

        panelArbol.setNodoResaltado(null);
        panelArbol.repaint();

        int superHeroes = arbol.contarPorCategoria("Super Heroes");
        int superVillanos = arbol.contarPorCategoria("Super Villanos");
        int totalCompuesto = superHeroes + superVillanos;

        String frasesIconicas = arbol.listarFrIc();
        String mayorMenor = arbol.obtenerMayorYMenor();

        txaDatos.setText(
            "CONSULTA EXTRA\n\n" +
            "1. TOTAL DE TARJETAS SUPER HEROES Y SUPER VILLANOS\n" +
            "Super Heroes: " + superHeroes + "\n" +
            "Super Villanos: " + superVillanos + "\n" +
            "Total compuesto: " + totalCompuesto + "\n\n" +

            "2. DESCRIPCIONES DE FRASES ICONICAS QUE SON NODOS HOJA\n" +
            frasesIconicas + "\n\n" +

            "3. NODOS CON MAYOR Y MENOR ID\n" +
            mayorMenor
        );

        mostrarEstadoTemporal("Consulta extra generada correctamente", Color.GREEN);
    }//GEN-LAST:event_btnConsultasAdicionalesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCantidadNodos;
    private javax.swing.JButton btnConsultasAdicionales;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnListarNodosHojas;
    private javax.swing.JButton btnMayorMenor;
    private javax.swing.JButton btnPostOrden;
    private javax.swing.JButton btnPreorden;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlGrafica;
    private javax.swing.JTextArea txaDatos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
